arduino_arm:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 25

    # Position Controllers ---------------------------------------
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_link1_joint
        pid: { p: 100.0, i: 1, d: 1.0 }

    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: link1_link2_joint
        pid: { p: 100.0, i: 1, d: 1.0 }

    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: link2_link3_joint
        pid: { p: 100.0, i: 1, d: 1.0 }