controller_list:
  - name: fake_arduino_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint
initial:  # Define initial robot poses per group
  - group: arduino_arm
    pose: resting_pose