controller_list:
  - name: "position_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint